### ISSUE TITLE
float와 double

### ISSUE THREAD

**Issue by 2kyung19** [2kyung19/rehabilitate#1]
![image](https://user-images.githubusercontent.com/32586712/72986285-3ad86f00-3e2b-11ea-9e17-0d328eb5e0c3.png)

왜이런걸까 float는 섬세한 친구인걸까

**Comment by riyenas0925** [comment]
@2kyung19 이미 찾아봤겠지만 부동소수점으로 정확하게 소수를 표현할수 없어서 생기는 오류
[부동 소수점(Floating Point)란 무엇인가?
](https://steemit.com/kr/@modolee/floating-point)

**Comment by 2kyung19** [comment]
@riyenas0925 🤭🤭

**Comment by 2kyung19** [comment]
@riyenas0925 놀라워요

**Comment by riyenas0925** [comment]
@2kyung19 엥 뭐여 이걸 바로 확인한다고?

**Comment by 2kyung19** [comment]
@riyenas0925 깃허브 망령...,,.갱동민씨...,, 궁금한거생기면 항상 이슈에 올리도록 하겠습니다^오^

**Comment by 2kyung19** [comment]
+ 추가
일반적으로 float 변수에 값을 할당할 땐
f1 = 5.1f (f를 붙임)
> 분명 배웠을 텐데 왜 기억이 없지
